#ifndef __AdminDlg__
#define __AdminDlg__

/**
@file
Subclass of AdminDlgGui, which is generated by wxFormBuilder.
*/

#include "AdminDlgGui.h"

//// end generated include

/** Implementing AdminDlgGui */
class AdminDlg : public AdminDlgGui
{
	protected:
		// Handlers for AdminDlgGui events.
		void OnButtonClickAdd( wxCommandEvent& event );
		void OnButtonClickDel( wxCommandEvent& event );
		void OnButtonClickUpdate( wxCommandEvent& event );

		void query();
		void select(const wxString& adminName);

	public:
		/** Constructor */
		AdminDlg( wxWindow* parent );
	//// end generated class members
	
};

#endif // __AdminDlg__
