#ifndef __ClassDlg__
#define __ClassDlg__

/**
@file
Subclass of ClassDlgGui, which is generated by wxFormBuilder.
*/

#include "ClassDlgGui.h"

//// end generated include


struct RegularClassDataObj;
struct CalendarClassDataObj;


/** Implementing ClassDlgGui */
class ClassDlg : public ClassDlgGui
{
	protected:
		// Handlers for ClassDlgGui events.
		void OnClickAddStudent( wxCommandEvent& event );
		void OnClickDelStudent( wxCommandEvent& event );
		void OnListStudentActivated( wxListEvent& event );
		void OnListStudentSelected( wxListEvent& event );
	public:
		/** Constructor */
		enum ModeType { REGULAR, CALENDAR };
		ClassDlg( wxWindow* parent, ModeType mode );
	//// end generated class members
		void SetClassValue(const RegularClassDataObj& c);
		void GetClassValue(RegularClassDataObj *pc);
		void SetClassValue(const CalendarClassDataObj& c);
		void GetClassValue(CalendarClassDataObj *pc);
};

#endif // __ClassDlg__
