#ifndef __StudentDlg__
#define __StudentDlg__

/**
@file
Subclass of StudentDlgGui, which is generated by wxFormBuilder.
*/

#include "StudentDlgGui.h"

//// end generated include

/** Implementing StudentDlgGui */
class StudentDlg : public StudentDlgGui
{
	protected:
		// Handlers for StudentDlgGui events.
		void OnSearch( wxCommandEvent& event );
		void OnClickAddStudent( wxCommandEvent& event );
		void OnClickDelStudent( wxCommandEvent& event );
		void OnListItemActivated( wxListEvent& event );

		void query(const wxString& nameOrPhone);
		void select(const wxString& studentName);

	public:
		/** Constructor */
		StudentDlg( wxWindow* parent );
	//// end generated class members
	
};

#endif // __StudentDlg__
