#ifndef __TeacherEditDlg__
#define __TeacherEditDlg__

/**
@file
Subclass of TeacherEditDlgGui, which is generated by wxFormBuilder.
*/

#include "TeacherDlgGui.h"

//// end generated include

/** Implementing TeacherEditDlgGui */
class TeacherEditDlg : public TeacherEditDlgGui
{
	protected:
		// Handlers for TeacherEditDlgGui events.
		void OnClass( wxGridEvent& event );

		const wxString _teacherName;

	public:
		/** Constructor */
		TeacherEditDlg( wxWindow* parent, const wxString& teacherName );
	//// end generated class members
		void showClass();	
};

#endif // __TeacherEditDlg__
