#ifndef __TeacherDlg__
#define __TeacherDlg__

/**
@file
Subclass of TeacherDlgGui, which is generated by wxFormBuilder.
*/

#include "TeacherDlgGui.h"

//// end generated include

/** Implementing TeacherDlgGui */
class TeacherDlg : public TeacherDlgGui
{
	protected:
		// Handlers for TeacherDlgGui events.
		void OnClickAddTeacher( wxCommandEvent& event );
		void OnClickDelTeacher( wxCommandEvent& event );
		void OnListItemActivated( wxListEvent& event );

		void query(const wxString& nameOrPhone);
		void select(const wxString& teacherName);

	public:
		/** Constructor */
		TeacherDlg( wxWindow* parent );
	//// end generated class members
	
};

#endif // __TeacherDlg__
